openapi: "3.0.0"
info:
  version: 1.0.0
  title: Profitov Apps API
  description: REST API For Profitov Apps Bot
servers:
  - url: https://profitovhome.com
    description: Optional server description, e.g. Main (production) server
paths:
  /api/apps/getAll:
    get:
      summary: List all Apps
      operationId: listApps
      tags:
        - Apps
      responses:
        '200':    # status code
          description: A JSON array of Apps
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Apps'
              example:
                - name: 'Cheetah Simulator'
                  package: 'com.cheetah.simulator'
                  geo: ['RU', 'UA', 'AZ']
                  os: 'Android'
                  status: 'live'
                  mark: false
                  icon: 'base64img'
        '403':    # status code
          description: User not found, check your API Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Пользователь не найден'
  /api/apps/get/{package}:
    get:
      summary: Info for a specific App
      operationId: showAppByPackage
      tags:
        - Apps
      responses:
        '200':    # status code
          description: A JSON array of Apps
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/App'
              example:
                name: 'Cheetah Simulator'
                package: 'com.cheetah.simulator'
                geo: ['RU', 'UA', 'AZ']
                os: 'Android'
                status: 'live'
                mark: false
                icon: 'base64img'
        '403':    # status code
          description: User not found, check your API Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Пользователь не найден'
        '404':    # status code
          description: App not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Приложение не найдено'
  /api/share/{package}:
    post:
      summary: Share Facebook ID's
      operationId: shareids
      tags:
        - Share
      requestBody: 
        required: true
        content:
          application/x-www-form-urlencoded:
            schema: 
              type: object
              properties:
                ids:
                  type: string
              required:
                - ids
      responses:
        '200':    # status code
          description: A JSON object with share id in our system
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AnswerForShare'
              example:
                - id: '61b85a9eaaba76be08d1a9ee'
                  message: 'Your id for this task is: 61b85a9eaaba76be08d1a9ee'
        '403':    # status code
          description: User not found, check your API Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Пользователь не найден'
        '404':    # status code
          description: App not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Приложение не найдено'
  /api/check/share/{share_id}:
    get:
      summary: Check share by ID
      operationId: checkshareids
      tags:
        - Share
      responses:
        '200':    # status code
          description: A JSON object of Share
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/ShareStatus'
              example:
                message: 'ok'
                shared: [123, 456, 789]
                blocked: ['blabla', 120, 'smth']
                appName: 'Cheetah Simulator'
                package: 'com.cheetah.simulator'
                method: 'share'
                isShared: true
        '403':    # status code
          description: User not found, check your API Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Пользователь не найден'
        '404':    # status code
          description: App not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Приложение не найдено'
  /api/check/app/{package}:
    get:
      summary: List of shares on App by User
      operationId: sharelistapp
      tags:
        - Share
      responses:
        '200':    # status code
          description: A JSON object of Share
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/ShareStatus'
              example:
                - message: 'ok'
                  shared: [123, 456, 789]
                  blocked: ['blabla', 120, 'smth']
                  appName: 'Cheetah Simulator'
                  package: 'com.cheetah.simulator'
                  method: 'share'
                  isShared: true
        '403':    # status code
          description: User not found, check your API Key
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Пользователь не найден'
        '404':    # status code
          description: App not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: 
                    type: string
              example:
                message: 'Приложение не найдено'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Apps:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          package:
            type: string
          geo:
            type: array
            items:
              type: string
          os: 
            type: string
          status:
            type: string
          mark: 
            type: boolean
          icon:
            type: string
    App:
      type: object
      properties:
        name:
          type: string
        package:
          type: string
        geo:
          type: array
          items:
            type: string
        os: 
          type: string
        status:
          type: string
        mark: 
          type: boolean
        icon:
          type: string
    AnswerForShare:
      type: object
      properties:
        id:
          type: string
        message:
          type: string
    ShareStatus:
      type: object
      properties:
        message:
          type: string
        shared:
          type: array
          items:
            type: string
        blocked:
          type: array
          items:
            type: any
        appName:
          type: string
        package:
          type: string
        method:
          type: string
        isShared:
          type: boolean
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
security:
  - ApiKeyAuth: []